# -*- coding: utf-8 -*-
"""Medical Insurance Payout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1if7U-h3oN80pBGfJP9c2CsT_lRShIW0I
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

dfC = pd.read_csv("ödemeTahmin.csv")

df = dfC.copy()

df.head(3)

df.tail(3)

df.info()

df.shape

df.describe().T

plt.figure(figsize= (17,6))
sns.lineplot(x= "age", y = "charges", data = df)
plt.title("Medical Fee Payable by Age", color = 'red')
plt.xlabel("Age")
plt.ylabel("Charges")
plt.xticks(rotation = 50)
plt.show()

plt.figure(figsize= (17,6))
plt.subplot(1,3,1)
sns.barplot(x= "sex", y= "charges", data = df, color = 'red')
plt.title("Health Fee Payable by Gender")
plt.xlabel("Sex")
plt.ylabel("Charges")
plt.xticks(rotation = 50)

plt.subplot(1,3,2)
sns.barplot(x = "region", y= "charges", data= df, color = 'green')
plt.title("Health Fee Payable by Region")
plt.xlabel("Region")
plt.ylabel("Charges")
plt.xticks(rotation = 50)

plt.subplot(1,3,3)
sns.barplot(x= "smoker", y= "charges", data = df, color = 'yellow')
plt.title("Health Insurance Paid by Distribution of Smokers")
plt.xlabel("Smoker")
plt.ylabel("Charges")
plt.xticks(rotation=50)

plt.tight_layout()
plt.show()

Correlation = df.select_dtypes(include=[float, int])

corr = Correlation.corr()

print(corr)

plt.figure(figsize= (17,6))
sns.heatmap(corr, annot=True, cmap= "Set3", fmt= ".2f", linewidths=0.5, linecolor="red")
plt.title("Displaying Correlation Values with Heat Map", color = 'red')
plt.show()

sex_counts = df['sex'].value_counts()
region_counts = df['region'].value_counts()
smoker_counts = df['smoker'].value_counts()

plt.figure(figsize= (17,6))
plt.subplot(1,3,1)
plt.pie(sex_counts, labels=sex_counts.index, autopct='%1.1f%%', colors=['#ff9999', '#66b3ff'])
plt.title("Distribution of Sex")

plt.subplot(1,3,2)
plt.pie(region_counts, labels=region_counts.index, autopct='%1.1f%%', colors=['#99ff99', '#ffcc99', '#c2c2f0', '#ffb3e6'])
plt.title("Distribution of Region")

plt.subplot(1,3,3)
plt.pie(smoker_counts, labels=smoker_counts.index, autopct='%1.1f%%', colors=['#ff6666', '#c4e17f'])
plt.title("Distribution of Smokers")

plt.tight_layout()
plt.show()

